from flask import Flask, render_template, request, send_file, redirect, url_for, flash
import requests
import io
import os
import re

app = Flask(__name__)
# Security ke liye random key
app.secret_key = os.urandom(24)

# In files ko priority order mein dhoondhega
ENV_FILES = ["config.env", ".env", "sample.env", ".env.sample", ".env.example", "env.example"]

def get_raw_url(repo_url, file_name, branch):
    """GitHub Repo URL se Raw File URL banata hai selected branch ke liye"""
    clean_url = repo_url.rstrip("/").rstrip(".git")
    
    if "github.com" in clean_url:
        try:
            parts = clean_url.split("github.com/")[-1].split("/")
            user = parts[0]
            repo = parts[1]
            return f"https://raw.githubusercontent.com/{user}/{repo}/{branch}/{file_name}"
        except IndexError:
            return None
    return None

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        repo_url = request.form.get('repo_url')
        branch = request.form.get('branch', 'master') # Form se branch lega, default master
        
        if not repo_url:
             flash("Please enter a valid GitHub URL.")
             return redirect(url_for('index'))

        found_content = None
        
        # Selected Branch par saare filenames check karo
        for env_name in ENV_FILES:
            raw_url = get_raw_url(repo_url, env_name, branch)
            if raw_url:
                try:
                    response = requests.get(raw_url, timeout=5)
                    if response.status_code == 200:
                        found_content = response.text
                        break
                except:
                    continue
        
        # Agar content mil gaya
        if found_content:
            # Regex use karke variables nikalo (Zyada accurate hai)
            # Ye pattern sirf 'VAR_NAME=' ko pakdega
            variables = re.findall(r'^([A-Z0-9_]+)\s?=', found_content, re.MULTILINE)
            
            # Duplicates hatao
            unique_vars = []
            seen = set()
            for var in variables:
                if var not in seen:
                    unique_vars.append(var)
                    seen.add(var)
            
            variables = unique_vars

            if not variables:
                 flash(f"File mil gayi ({branch} branch par), par variables nahi dikhe.")
                 return redirect(url_for('index'))

            # HTML ko variables bhej rahe hain
            return render_template('index.html', variables=variables, repo_url=repo_url, branch=branch, step="fill_form")
        
        else:
            flash(f"Is Repo ke '{branch}' branch mein koi env file nahi mili.")
            return redirect(url_for('index'))

    # Pehli baar page load hone par
    return render_template('index.html', step="input_repo")

@app.route('/download', methods=['POST'])
def download():
    """Download button dabane par ye chalega"""
    env_content = ""
    # Header comment (Optional)
    env_content += "# Generated by Sudeep Env Tool\n\n"

    for key, value in request.form.items():
        # Repo URL aur Branch ko file mein mat likho, baaki sab likho
        if key not in ["repo_url", "branch"]:
            env_content += f"{key}={value}\n"
    
    # Memory file create karo
    mem_file = io.BytesIO()
    mem_file.write(env_content.encode('utf-8'))
    mem_file.seek(0)
    
    return send_file(
        mem_file,
        as_attachment=True,
        download_name='.env',
        mimetype='text/plain'
    )

if __name__ == '__main__':
    app.run(debug=True)
    
